/* Generated By:JavaCC: Do not edit this line. YakaConstants.java */
public interface YakaConstants {

  int EOF = 0;
  int BOOLEAN = 8;
  int VAR = 9;
  int DO = 10;
  int ELSE = 11;
  int FOR = 12;
  int IF = 13;
  int FI = 14;
  int INT = 15;
  int RETURN = 16;
  int TRUE = 17;
  int WHILE = 18;
  int CONST = 19;
  int FALSE = 20;
  int DONE = 21;
  int OR = 22;
  int AND = 23;
  int NOT = 24;
  int FUNCTION = 25;
  int EFUNCTION = 26;
  int PROGRAM = 27;
  int EPROGRAM = 28;
  int MAIN = 29;
  int EMAIN = 30;
  int THEN = 31;
  int WRITE = 32;
  int READ = 33;
  int GOTOLINE = 34;
  int PLUS = 35;
  int MINUS = 36;
  int DIV = 37;
  int MUL = 38;
  int EQU = 39;
  int DIF = 40;
  int INF = 41;
  int EINF = 42;
  int SUP = 43;
  int ESUP = 44;
  int figure = 45;
  int integer = 46;
  int letter = 47;
  int ident = 48;
  int string = 49;

  int DEFAULT = 0;
  int IN_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(*\"",
    "<token of kind 6>",
    "\"*)\"",
    "\"BOOLEEN\"",
    "\"VAR\"",
    "\"FAIRE\"",
    "\"SINON\"",
    "\"POUR\"",
    "\"SI\"",
    "\"FSI\"",
    "\"ENTIER\"",
    "\"RETOURNE\"",
    "\"VRAI\"",
    "\"TANTQUE\"",
    "\"CONST\"",
    "\"FAUX\"",
    "\"FAIT\"",
    "\"OU\"",
    "\"ET\"",
    "\"NON\"",
    "\"FONCTION\"",
    "\"FFONCTION\"",
    "\"PROGRAMME\"",
    "\"FPROGRAMME\"",
    "\"PRINCIPAL\"",
    "\"FPRINCIPAL\"",
    "\"ALORS\"",
    "\"ECRIRE\"",
    "\"LIRE\"",
    "\"ALALIGNE\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"=\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "<figure>",
    "<integer>",
    "<letter>",
    "<ident>",
    "<string>",
    "\",\"",
    "\";\"",
    "\"(\"",
    "\")\"",
  };

}
