/* Generated By:JavaCC: Do not edit this line. YakaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface YakaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BOOLEAN = 8;
  /** RegularExpression Id. */
  int VAR = 9;
  /** RegularExpression Id. */
  int DO = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int FOR = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int FI = 14;
  /** RegularExpression Id. */
  int INT = 15;
  /** RegularExpression Id. */
  int RETURN = 16;
  /** RegularExpression Id. */
  int TRUE = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int CONST = 19;
  /** RegularExpression Id. */
  int FALSE = 20;
  /** RegularExpression Id. */
  int DONE = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int AND = 23;
  /** RegularExpression Id. */
  int NOT = 24;
  /** RegularExpression Id. */
  int FUNCTION = 25;
  /** RegularExpression Id. */
  int EFUNCTION = 26;
  /** RegularExpression Id. */
  int PROGRAM = 27;
  /** RegularExpression Id. */
  int EPROGRAM = 28;
  /** RegularExpression Id. */
  int MAIN = 29;
  /** RegularExpression Id. */
  int EMAIN = 30;
  /** RegularExpression Id. */
  int THEN = 31;
  /** RegularExpression Id. */
  int WRITE = 32;
  /** RegularExpression Id. */
  int READ = 33;
  /** RegularExpression Id. */
  int GOTOLINE = 34;
  /** RegularExpression Id. */
  int PLUS = 35;
  /** RegularExpression Id. */
  int MINUS = 36;
  /** RegularExpression Id. */
  int DIV = 37;
  /** RegularExpression Id. */
  int MUL = 38;
  /** RegularExpression Id. */
  int EQU = 39;
  /** RegularExpression Id. */
  int DIF = 40;
  /** RegularExpression Id. */
  int INF = 41;
  /** RegularExpression Id. */
  int EINF = 42;
  /** RegularExpression Id. */
  int SUP = 43;
  /** RegularExpression Id. */
  int ESUP = 44;
  /** RegularExpression Id. */
  int figure = 45;
  /** RegularExpression Id. */
  int integer = 46;
  /** RegularExpression Id. */
  int letter = 47;
  /** RegularExpression Id. */
  int ident = 48;
  /** RegularExpression Id. */
  int string = 49;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(*\"",
    "<token of kind 6>",
    "\"*)\"",
    "\"BOOLEEN\"",
    "\"VAR\"",
    "\"FAIRE\"",
    "\"SINON\"",
    "\"POUR\"",
    "\"SI\"",
    "\"FSI\"",
    "\"ENTIER\"",
    "\"RETOURNE\"",
    "\"VRAI\"",
    "\"TANTQUE\"",
    "\"CONST\"",
    "\"FAUX\"",
    "\"FAIT\"",
    "\"OU\"",
    "\"ET\"",
    "\"NON\"",
    "\"FONCTION\"",
    "\"FFONCTION\"",
    "\"PROGRAMME\"",
    "\"FPROGRAMME\"",
    "\"PRINCIPAL\"",
    "\"FPRINCIPAL\"",
    "\"ALORS\"",
    "\"ECRIRE\"",
    "\"LIRE\"",
    "\"ALALIGNE\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"=\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "<figure>",
    "<integer>",
    "<letter>",
    "<ident>",
    "<string>",
    "\",\"",
    "\";\"",
    "\"(\"",
    "\")\"",
  };

}
